#!/bin/bash
path=`pwd`
version='0.1.1'
while getopts "p:" arg;
do
	case $arg in
	  p)
	    path=${OPTARG}
	    ;;
	esac
done
mkdir -p $path/scIGANs${version}/
cp -r src $path/scIGANs${version}/
cp scIGANs $path/scIGANs${version}/
chmod +x $path/scIGANs${version}/scIGANs
echo "export PATH=${path}/scIGANs${version}/:$PATH" >> ~/.bashrc
source ~/.bashrc
export PATH=${path}/scIGANs${version}/:$PATH
echo 'scIGANs was installed in '${path}/scIGANs${version}/

